[2018-04-18 03:23:28,342] WARN Client session timed out, have not heard from server in 1523508ms for sessionid 0x3001d761fb0000b (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:28,782] INFO Client session timed out, have not heard from server in 1523508ms for sessionid 0x3001d761fb0000b, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:28,460] INFO [Partition wing-binlog-event-1 broker=2] Shrinking ISR from 0,2,1 to 2 (kafka.cluster.Partition)
[2018-04-18 03:23:29,008] INFO Opening socket connection to server 127.0.0.1/127.0.0.1:12182. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,008] INFO Socket connection established to 127.0.0.1/127.0.0.1:12182, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,187] WARN Unable to reconnect to ZooKeeper service, session 0x3001d761fb0000b has expired (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,187] INFO Unable to reconnect to ZooKeeper service, session 0x3001d761fb0000b has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,188] INFO [ZooKeeperClient] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2018-04-18 03:23:29,188] INFO EventThread shut down for session: 0x3001d761fb0000b (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,198] INFO [ZooKeeperClient] Initializing a new session to 127.0.0.1:12181,127.0.0.1:12182,127.0.0.1:12183. (kafka.zookeeper.ZooKeeperClient)
[2018-04-18 03:23:29,198] INFO Initiating client connection, connectString=127.0.0.1:12181,127.0.0.1:12182,127.0.0.1:12183 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@3c130745 (org.apache.zookeeper.ZooKeeper)
[2018-04-18 03:23:29,202] INFO Opening socket connection to server 127.0.0.1/127.0.0.1:12183. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,204] INFO Creating /brokers/ids/2 (is it secure? false) (kafka.zk.KafkaZkClient)
[2018-04-18 03:23:29,206] INFO Socket connection established to 127.0.0.1/127.0.0.1:12183, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,221] INFO Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,333] ERROR Uncaught exception in scheduled task 'isr-expiration' (kafka.utils.KafkaScheduler)
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /brokers/topics/wing-binlog-event/partitions/1/state
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at kafka.zookeeper.AsyncResponse.resultException(ZooKeeperClient.scala:465)
	at kafka.zk.KafkaZkClient.conditionalUpdatePath(KafkaZkClient.scala:621)
	at kafka.utils.ReplicationUtils$.updateLeaderAndIsr(ReplicationUtils.scala:34)
	at kafka.cluster.Partition.updateIsr(Partition.scala:670)
	at kafka.cluster.Partition.$anonfun$maybeShrinkIsr$1(Partition.scala:513)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:250)
	at kafka.utils.CoreUtils$.inWriteLock(CoreUtils.scala:258)
	at kafka.cluster.Partition.maybeShrinkIsr(Partition.scala:504)
	at kafka.server.ReplicaManager.$anonfun$maybeShrinkIsr$2(ReplicaManager.scala:1335)
	at kafka.server.ReplicaManager.$anonfun$maybeShrinkIsr$2$adapted(ReplicaManager.scala:1335)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at kafka.server.ReplicaManager.maybeShrinkIsr(ReplicaManager.scala:1335)
	at kafka.server.ReplicaManager.$anonfun$startup$1(ReplicaManager.scala:322)
	at kafka.utils.KafkaScheduler.$anonfun$schedule$2(KafkaScheduler.scala:110)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-04-18 03:23:29,338] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2018-04-18 03:23:29,338] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2018-04-18 03:23:29,787] INFO Opening socket connection to server 127.0.0.1/127.0.0.1:12182. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:29,789] INFO Socket connection established to 127.0.0.1/127.0.0.1:12182, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:30,646] INFO Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:31,594] INFO Opening socket connection to server 127.0.0.1/127.0.0.1:12181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:31,595] INFO Socket connection established to 127.0.0.1/127.0.0.1:12181, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:31,614] INFO Session establishment complete on server 127.0.0.1/127.0.0.1:12181, sessionid = 0x1002434d1da0002, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2018-04-18 03:23:31,614] INFO [ZooKeeperClient] Connected. (kafka.zookeeper.ZooKeeperClient)
[2018-04-18 03:23:31,614] INFO [ZooKeeperClient] Connected. (kafka.zookeeper.ZooKeeperClient)
[2018-04-18 03:23:31,641] ERROR Error while creating ephemeral at /brokers/ids/2, node already exists and owner '216205175288758283' does not match current session '72097403315552258' (kafka.zk.KafkaZkClient$CheckedEphemeral)
[2018-04-18 03:23:31,641] INFO Result of znode creation at /brokers/ids/2 is: NODEEXISTS (kafka.zk.KafkaZkClient)
